spring:
  application:
    name: api-gateway

server:
  port: 80

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

# 路由规则
zuul:
  routes:
    product-service:
      path: /product-service/**
      service-id: product-service


zuul:
  routes:
    ui-service:
      path: /ui-service/**
      service-id: ui-service
